# Generated by Django 5.1.6 on 2025-02-28 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_portal', '0002_course_studymaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_teacher',
        ),
    ]
