# Generated by Django 5.1.6 on 2025-03-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_portal', '0004_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='category',
            field=models.CharField(choices=[('note', 'Note'), ('question_paper', 'Question Paper'), ('scheme', 'Scheme & Application'), ('result', 'Result')], default='note', max_length=20),
            preserve_default=False,
        ),
    ]
